In [1]:
!nvidia-smi

Sun Apr 17 20:58:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   30C    P0    31W / 250W |   8717MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   31C    P0    31W / 250W |    377MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

In [2]:
!pip install scikit-multilearn

In [3]:
import numpy as np

In [142]:
# Tao du lieu
from sklearn.datasets import make_multilabel_classification

X, y = make_multilabel_classification(n_samples = 100, n_features = 20, n_classes = 5, sparse=False, n_labels=2,
                                     return_indicator="dense", allow_unlabeled= False)

X, y

(array([[3., 4., 3., ..., 2., 4., 0.],
        [1., 5., 4., ..., 0., 1., 0.],
        [6., 2., 1., ..., 0., 2., 1.],
        ...,
        [3., 6., 3., ..., 3., 2., 3.],
        [2., 1., 1., ..., 0., 5., 0.],
        [1., 2., 2., ..., 1., 3., 3.]]),
 array([[0, 0, 1, 0, 1],
        [1, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 1],
        [1, 1, 0, 1, 0],
        [1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0],
        [1, 0, 0, 0, 0],
        [1, 1, 0, 1, 0],
        [1, 1, 0, 1, 1],
        [1, 1, 0, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 1, 1],
        [1, 0, 0, 1, 1],
        [0, 1, 0, 1, 0],
        [0, 1, 1, 1, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [1, 1, 0, 1, 1],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 1, 0],
        [1, 1, 0, 1, 0],
 

In [143]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [120]:
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import GaussianNB

# Khoi tao
br_clf = BinaryRelevance(GaussianNB())

# Train 
br_clf.fit(X_train, y_train)

# Du doan
y_pred = br_clf.predict(X_test)

In [124]:
def hamming_score(y_true, y_pred, normalize=True, sample_weight=None):
    '''
    Compute the Hamming score (a.k.a. label-based accuracy) for the multi-label case
    http://stackoverflow.com/q/32239577/395857
    '''
    acc_list = []
    for i in range(y_true.shape[0]):
        set_true = set( np.where(y_true[i])[0] )
        set_pred = set( np.where(y_pred[i])[0] )
        #print('\nset_true: {0}'.format(set_true))
        #print('set_pred: {0}'.format(set_pred))
        tmp_a = None
        if len(set_true) == 0 and len(set_pred) == 0:
            tmp_a = 1
        else:
            tmp_a = len(set_true.intersection(set_pred))/\
                    float( len(set_true.union(set_pred)) )
        #print('tmp_a: {0}'.format(tmp_a))
        acc_list.append(tmp_a)
    return np.mean(acc_list)

In [126]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred.todense(), y_test))
print(hamming_score(np.array(y_pred.todense()), y_test))

0.0
0.5833333333333333


In [132]:
y_pred.todense(), y_test

(matrix([[0, 0, 0, 0, 1],
         [0, 0, 0, 0, 1],
         [0, 0, 1, 0, 1],
         [0, 0, 1, 0, 1]]),
 array([[0, 0, 1, 1, 0],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [0, 0, 1, 1, 1]]))

In [127]:
from skmultilearn.problem_transform import ClassifierChain
from sklearn.naive_bayes import GaussianNB

# Khoi tao
cc_clf = ClassifierChain(GaussianNB())

# Train 
cc_clf.fit(X_train, y_train)

# Du doan
y_pred = cc_clf.predict(X_test)

In [128]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred.todense(), y_test))
print(hamming_score(np.array(y_pred.todense()), y_test))

0.0
0.5208333333333333


In [130]:
from skmultilearn.problem_transform import LabelPowerset
from sklearn.naive_bayes import GaussianNB

# Khoi tao
lp_clf = LabelPowerset(GaussianNB())

# Train 
lp_clf.fit(X_train, y_train)

# Du doan
y_pred = lp_clf.predict(X_test)

In [131]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred.todense(), y_test))
print(hamming_score(np.array(y_pred.todense()), y_test))

0.0
0.35416666666666663


In [136]:
from skmultilearn.adapt import MLkNN

# Khoi tao
mlknn_clf = MLkNN(k=5)

# Fit
mlknn_clf.fit(X_train, y_train)

# Du doan
y_pred = mlknn_clf.predict(X_test)

/home/anhpv/.conda/envs/mtcnn/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_neighbors=5 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [137]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred.todense(), y_test))
print(hamming_score(np.array(y_pred.todense()), y_test))

0.0
0.2708333333333333


In [138]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow

In [140]:
model = Sequential()
model.add(Dense(32, input_dim = X.shape[1], activation="relu"))
model.add(Dense(y.shape[1], activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer = "adam", metrics=['accuracy', 'binary_accuracy'])

In [146]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=16)

Epoch 1/10
5/5 [==============================] - 0s 18ms/step - loss: 0.7558 - accuracy: 0.1250 - binary_accuracy: 0.5675 - val_loss: 0.8747 - val_accuracy: 0.1000 - val_binary_accuracy: 0.4900
Epoch 2/10
5/5 [==============================] - 0s 12ms/step - loss: 0.7304 - accuracy: 0.1750 - binary_accuracy: 0.5775 - val_loss: 0.8584 - val_accuracy: 0.1500 - val_binary_accuracy: 0.5400
Epoch 3/10
5/5 [==============================] - 0s 11ms/step - loss: 0.7100 - accuracy: 0.2375 - binary_accuracy: 0.5975 - val_loss: 0.8452 - val_accuracy: 0.1500 - val_binary_accuracy: 0.5700
Epoch 4/10
5/5 [==============================] - 0s 9ms/step - loss: 0.6900 - accuracy: 0.2750 - binary_accuracy: 0.6175 - val_loss: 0.8353 - val_accuracy: 0.1500 - val_binary_accuracy: 0.5800
Epoch 5/10
5/5 [==============================] - 0s 9ms/step - loss: 0.6730 - accuracy: 0.3000 - binary_accuracy: 0.6275 - val_loss: 0.8270 - val_accuracy: 0.2000 - val_binary_accuracy: 0.5900
Epoch 6/10
5/5 [===========

In [145]:
X_train.shape

(80, 20)